# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marrero/Master_Informatica/Sistemas_Inteligentes/MRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marrero/Master_Informatica/Sistemas_Inteligentes/MRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marrero/Master_Informatica/Sistemas_Inteligentes/MRT/CMakeFiles /home/marrero/Master_Informatica/Sistemas_Inteligentes/MRT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marrero/Master_Informatica/Sistemas_Inteligentes/MRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MRT

# Build rule for target.
MRT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MRT
.PHONY : MRT

# fast build rule for target.
MRT/fast:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/build
.PHONY : MRT/fast

src/Algorithms/Greedy.o: src/Algorithms/Greedy.cpp.o

.PHONY : src/Algorithms/Greedy.o

# target to build an object file
src/Algorithms/Greedy.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/Greedy.cpp.o
.PHONY : src/Algorithms/Greedy.cpp.o

src/Algorithms/Greedy.i: src/Algorithms/Greedy.cpp.i

.PHONY : src/Algorithms/Greedy.i

# target to preprocess a source file
src/Algorithms/Greedy.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/Greedy.cpp.i
.PHONY : src/Algorithms/Greedy.cpp.i

src/Algorithms/Greedy.s: src/Algorithms/Greedy.cpp.s

.PHONY : src/Algorithms/Greedy.s

# target to generate assembly for a file
src/Algorithms/Greedy.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/Greedy.cpp.s
.PHONY : src/Algorithms/Greedy.cpp.s

src/Algorithms/LocalSearch.o: src/Algorithms/LocalSearch.cpp.o

.PHONY : src/Algorithms/LocalSearch.o

# target to build an object file
src/Algorithms/LocalSearch.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/LocalSearch.cpp.o
.PHONY : src/Algorithms/LocalSearch.cpp.o

src/Algorithms/LocalSearch.i: src/Algorithms/LocalSearch.cpp.i

.PHONY : src/Algorithms/LocalSearch.i

# target to preprocess a source file
src/Algorithms/LocalSearch.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/LocalSearch.cpp.i
.PHONY : src/Algorithms/LocalSearch.cpp.i

src/Algorithms/LocalSearch.s: src/Algorithms/LocalSearch.cpp.s

.PHONY : src/Algorithms/LocalSearch.s

# target to generate assembly for a file
src/Algorithms/LocalSearch.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/LocalSearch.cpp.s
.PHONY : src/Algorithms/LocalSearch.cpp.s

src/Algorithms/Metaheuristic.o: src/Algorithms/Metaheuristic.cpp.o

.PHONY : src/Algorithms/Metaheuristic.o

# target to build an object file
src/Algorithms/Metaheuristic.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/Metaheuristic.cpp.o
.PHONY : src/Algorithms/Metaheuristic.cpp.o

src/Algorithms/Metaheuristic.i: src/Algorithms/Metaheuristic.cpp.i

.PHONY : src/Algorithms/Metaheuristic.i

# target to preprocess a source file
src/Algorithms/Metaheuristic.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/Metaheuristic.cpp.i
.PHONY : src/Algorithms/Metaheuristic.cpp.i

src/Algorithms/Metaheuristic.s: src/Algorithms/Metaheuristic.cpp.s

.PHONY : src/Algorithms/Metaheuristic.s

# target to generate assembly for a file
src/Algorithms/Metaheuristic.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/Metaheuristic.cpp.s
.PHONY : src/Algorithms/Metaheuristic.cpp.s

src/Algorithms/SimulatedAnnealing.o: src/Algorithms/SimulatedAnnealing.cpp.o

.PHONY : src/Algorithms/SimulatedAnnealing.o

# target to build an object file
src/Algorithms/SimulatedAnnealing.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/SimulatedAnnealing.cpp.o
.PHONY : src/Algorithms/SimulatedAnnealing.cpp.o

src/Algorithms/SimulatedAnnealing.i: src/Algorithms/SimulatedAnnealing.cpp.i

.PHONY : src/Algorithms/SimulatedAnnealing.i

# target to preprocess a source file
src/Algorithms/SimulatedAnnealing.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/SimulatedAnnealing.cpp.i
.PHONY : src/Algorithms/SimulatedAnnealing.cpp.i

src/Algorithms/SimulatedAnnealing.s: src/Algorithms/SimulatedAnnealing.cpp.s

.PHONY : src/Algorithms/SimulatedAnnealing.s

# target to generate assembly for a file
src/Algorithms/SimulatedAnnealing.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/SimulatedAnnealing.cpp.s
.PHONY : src/Algorithms/SimulatedAnnealing.cpp.s

src/Algorithms/TabuSearch.o: src/Algorithms/TabuSearch.cpp.o

.PHONY : src/Algorithms/TabuSearch.o

# target to build an object file
src/Algorithms/TabuSearch.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/TabuSearch.cpp.o
.PHONY : src/Algorithms/TabuSearch.cpp.o

src/Algorithms/TabuSearch.i: src/Algorithms/TabuSearch.cpp.i

.PHONY : src/Algorithms/TabuSearch.i

# target to preprocess a source file
src/Algorithms/TabuSearch.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/TabuSearch.cpp.i
.PHONY : src/Algorithms/TabuSearch.cpp.i

src/Algorithms/TabuSearch.s: src/Algorithms/TabuSearch.cpp.s

.PHONY : src/Algorithms/TabuSearch.s

# target to generate assembly for a file
src/Algorithms/TabuSearch.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/TabuSearch.cpp.s
.PHONY : src/Algorithms/TabuSearch.cpp.s

src/Algorithms/VNS.o: src/Algorithms/VNS.cpp.o

.PHONY : src/Algorithms/VNS.o

# target to build an object file
src/Algorithms/VNS.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/VNS.cpp.o
.PHONY : src/Algorithms/VNS.cpp.o

src/Algorithms/VNS.i: src/Algorithms/VNS.cpp.i

.PHONY : src/Algorithms/VNS.i

# target to preprocess a source file
src/Algorithms/VNS.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/VNS.cpp.i
.PHONY : src/Algorithms/VNS.cpp.i

src/Algorithms/VNS.s: src/Algorithms/VNS.cpp.s

.PHONY : src/Algorithms/VNS.s

# target to generate assembly for a file
src/Algorithms/VNS.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Algorithms/VNS.cpp.s
.PHONY : src/Algorithms/VNS.cpp.s

src/Basis/Location.o: src/Basis/Location.cpp.o

.PHONY : src/Basis/Location.o

# target to build an object file
src/Basis/Location.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Location.cpp.o
.PHONY : src/Basis/Location.cpp.o

src/Basis/Location.i: src/Basis/Location.cpp.i

.PHONY : src/Basis/Location.i

# target to preprocess a source file
src/Basis/Location.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Location.cpp.i
.PHONY : src/Basis/Location.cpp.i

src/Basis/Location.s: src/Basis/Location.cpp.s

.PHONY : src/Basis/Location.s

# target to generate assembly for a file
src/Basis/Location.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Location.cpp.s
.PHONY : src/Basis/Location.cpp.s

src/Basis/Map.o: src/Basis/Map.cpp.o

.PHONY : src/Basis/Map.o

# target to build an object file
src/Basis/Map.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Map.cpp.o
.PHONY : src/Basis/Map.cpp.o

src/Basis/Map.i: src/Basis/Map.cpp.i

.PHONY : src/Basis/Map.i

# target to preprocess a source file
src/Basis/Map.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Map.cpp.i
.PHONY : src/Basis/Map.cpp.i

src/Basis/Map.s: src/Basis/Map.cpp.s

.PHONY : src/Basis/Map.s

# target to generate assembly for a file
src/Basis/Map.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Map.cpp.s
.PHONY : src/Basis/Map.cpp.s

src/Basis/Route.o: src/Basis/Route.cpp.o

.PHONY : src/Basis/Route.o

# target to build an object file
src/Basis/Route.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Route.cpp.o
.PHONY : src/Basis/Route.cpp.o

src/Basis/Route.i: src/Basis/Route.cpp.i

.PHONY : src/Basis/Route.i

# target to preprocess a source file
src/Basis/Route.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Route.cpp.i
.PHONY : src/Basis/Route.cpp.i

src/Basis/Route.s: src/Basis/Route.cpp.s

.PHONY : src/Basis/Route.s

# target to generate assembly for a file
src/Basis/Route.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Route.cpp.s
.PHONY : src/Basis/Route.cpp.s

src/Basis/Tourist.o: src/Basis/Tourist.cpp.o

.PHONY : src/Basis/Tourist.o

# target to build an object file
src/Basis/Tourist.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Tourist.cpp.o
.PHONY : src/Basis/Tourist.cpp.o

src/Basis/Tourist.i: src/Basis/Tourist.cpp.i

.PHONY : src/Basis/Tourist.i

# target to preprocess a source file
src/Basis/Tourist.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Tourist.cpp.i
.PHONY : src/Basis/Tourist.cpp.i

src/Basis/Tourist.s: src/Basis/Tourist.cpp.s

.PHONY : src/Basis/Tourist.s

# target to generate assembly for a file
src/Basis/Tourist.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/Basis/Tourist.cpp.s
.PHONY : src/Basis/Tourist.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/MRT.dir/build.make CMakeFiles/MRT.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... MRT"
	@echo "... edit_cache"
	@echo "... src/Algorithms/Greedy.o"
	@echo "... src/Algorithms/Greedy.i"
	@echo "... src/Algorithms/Greedy.s"
	@echo "... src/Algorithms/LocalSearch.o"
	@echo "... src/Algorithms/LocalSearch.i"
	@echo "... src/Algorithms/LocalSearch.s"
	@echo "... src/Algorithms/Metaheuristic.o"
	@echo "... src/Algorithms/Metaheuristic.i"
	@echo "... src/Algorithms/Metaheuristic.s"
	@echo "... src/Algorithms/SimulatedAnnealing.o"
	@echo "... src/Algorithms/SimulatedAnnealing.i"
	@echo "... src/Algorithms/SimulatedAnnealing.s"
	@echo "... src/Algorithms/TabuSearch.o"
	@echo "... src/Algorithms/TabuSearch.i"
	@echo "... src/Algorithms/TabuSearch.s"
	@echo "... src/Algorithms/VNS.o"
	@echo "... src/Algorithms/VNS.i"
	@echo "... src/Algorithms/VNS.s"
	@echo "... src/Basis/Location.o"
	@echo "... src/Basis/Location.i"
	@echo "... src/Basis/Location.s"
	@echo "... src/Basis/Map.o"
	@echo "... src/Basis/Map.i"
	@echo "... src/Basis/Map.s"
	@echo "... src/Basis/Route.o"
	@echo "... src/Basis/Route.i"
	@echo "... src/Basis/Route.s"
	@echo "... src/Basis/Tourist.o"
	@echo "... src/Basis/Tourist.i"
	@echo "... src/Basis/Tourist.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

